### ISSUE TITLE
Arreglar campos de formulario de registro

### ISSUE THREAD

**Issue by olemornav** [Cohabify/Cohabify#236]
Los errores se dan en el registro normal

- [x] Campos de contraseñas ya no validan la política
- [x] Campo de nombre de usuario me deja escribir más de 14 caracteres pero luego no deja registrarse por este motivo
- [x] Campo de email deja escribir un único carácter y si copias y pegas ya no te deja editar el email

**Comment by Miguel-Angel-Roldan-Garcia** [comment]
Se ha corregido en esta issue también un error que provocaba que se pudiera comentar en un anuncio de vivienda sin estar logeado.
