### ISSUE TITLE
Arreglar filtros de viviendas y users

### ISSUE THREAD

**Issue by olemornav** [Cohabify/Cohabify#257]
Errores a arreglar:

- [ ] El filtro por fecha en usuarios rompe la pantalla al darle a la "x" roja
- [ ]  El filtro de máximo número de inquilinos no funciona bien o no se expresa correctamente en la pantalla
- [ ] Los filtros de viviendas para número de habitaciones y número de baños no funcionan
- [ ] El filtro de vivienda vacía no funciona
- [ ] Probar a combinar los filtros y que sigan funcionando

**Comment by guigalde** [comment]
A mi no se me rompe la pantalla con lo de la x en la pantalla de usuarios.

**Comment by olemornav** [comment]
¿En el filtro de fechas si le das al botoncito rojo con una x no se te rompe la vista?

**Comment by olemornav** [comment]
Dani lo estuvo probando y dijo que era porque ponía un null me parece
